"""Generate per-site OpenResty server blocks and trigger an engine reload.

Site topology (domain / listen / origin) lives in nginx config files, so adding
or changing a site requires regenerating conf.d and reloading nginx. Rule/list
changes do NOT need this (they hot-sync via Redis).
"""
from __future__ import annotations

import asyncio
import logging
import os
import subprocess
import tempfile
from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.constants.engine_settings import (
    DEFAULT_MAX_UPLOAD_SIZE_MB,
    DEFAULT_ORIGIN_READ_TIMEOUT_SEC,
)
from app.core.redis import get_redis
from app.constants.client_ip import REAL_IP_HEADER_BY_SOURCE
from app.models import Site
from app.services.origin import build_upstream_url
from app.services.site_domains import site_domain_list
from app.services.listen_ports import (
    https_redirect_url,
    resolve_http_listen_ports,
    resolve_https_listen_ports,
)

log = logging.getLogger("waf.nginx_conf")

RELOAD_KEY = "waf:nginx:reload"
ENGINE_NGINX_CONF = "/usr/local/openresty/nginx/conf/nginx.conf"
ENGINE_PID_PATH = "/usr/local/openresty/nginx/logs/nginx.pid"
ENGINE_RELOAD_CMD = (
    "/usr/local/openresty/bin/openresty",
    "-s",
    "reload",
    "-c",
    ENGINE_NGINX_CONF,
)


def render_client_max_body_size(mb: int) -> str:
    """Render the http-level Nginx snippet for the configured upload cap."""
    size = int(mb) if mb else DEFAULT_MAX_UPLOAD_SIZE_MB
    return f"client_max_body_size {size}m;\n"


def _write_text_atomic(path: str, content: str) -> None:
    """Replace ``path`` via a same-directory temp file so reload never reads a truncated snippet."""
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".waf-snippet.", suffix=".tmp", dir=directory or None)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def apply_client_max_body_size(mb: int) -> None:
    """Write client_max_body_size so OpenResty picks it up on the next reload."""
    _write_text_atomic(settings.engine_client_max_body_conf, render_client_max_body_size(mb))


def render_origin_read_timeout(sec: int) -> str:
    """Render http-level origin proxy timeouts (read + send)."""
    timeout = int(sec) if sec else DEFAULT_ORIGIN_READ_TIMEOUT_SEC
    return (
        f"proxy_read_timeout {timeout}s;\n"
        f"proxy_send_timeout {timeout}s;\n"
    )


def apply_origin_read_timeout(sec: int) -> None:
    """Write origin proxy timeouts so OpenResty picks them up on the next reload."""
    _write_text_atomic(settings.engine_origin_timeout_conf, render_origin_read_timeout(sec))


@dataclass(frozen=True)
class EngineReloadResult:
    """Result of regenerating conf.d and reloading OpenResty.

    Truthy when reload succeeded, so existing ``if await regenerate(...)`` callers
    keep working. On failure, ``reason`` is a coarse class and ``detail`` carries
    the raw engine/OS error for user-facing messages.
    """

    ok: bool
    reason: str | None = None  # "certificate" | "engine" | None
    detail: str | None = None

    def __bool__(self) -> bool:
        return self.ok


def classify_reload_error(output: str) -> str:
    """Map nginx reload stderr to a stable failure reason."""
    text = (output or "").lower()
    cert_markers = (
        "cannot load certificate",
        "cannot load certificate key",
        "pem_read_bio",
        "ssl: error",
        "ssl_certificate",
        "x509",
        "asn1",
    )
    if any(marker in text for marker in cert_markers):
        return "certificate"
    return "engine"


def format_reload_warn_message(
    result: EngineReloadResult,
    *,
    saved_label: str = "站点已保存",
) -> str:
    """Build a user-facing soft-fail tip that always includes concrete detail when known."""
    detail = " ".join((result.detail or "").split()).strip()
    if result.reason == "certificate":
        head = f"{saved_label}，但证书异常，无法重载引擎"
        fallback = "请检查并更新证书后再次保存"
    else:
        head = f"{saved_label}，但 WAF 引擎配置重载失败"
        fallback = "请检查引擎状态后再次保存或重启容器"
    if detail:
        if len(detail) > 800:
            detail = detail[:800] + "…"
        return f"{head}：{detail}"
    return f"{head}，{fallback}"

# HTTP-01 challenge must win over WAF (server-level access.lua) and HTTPS redirects.
_ACME_CHALLENGE_LOCATION = """    location ^~ /.well-known/acme-challenge/ {{
        access_by_lua_block {{ return }}
        alias /data/acme/http-01/;
        default_type text/plain;
    }}
"""

_FIXED_TEMPLATE = """# generated by WAF backend - do not edit manually
server {{
{listen_lines}    server_name {domain};
    set $waf_site_id "{site_id}";
{real_ip_block}
    include /etc/nginx/snippets/waf.conf;
{ssl_block}
""" + _ACME_CHALLENGE_LOCATION + """    location / {{
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        # Use WAF-resolved client IP (access.lua → $waf_geoip_client), not TCP peer.
        proxy_set_header X-Real-IP $waf_geoip_client;
        proxy_set_header X-Forwarded-For $waf_geoip_client;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $waf_connection_upgrade;
        proxy_set_header X-WAF-Request-Id $waf_request_id;
{proxy_buffering_line}        proxy_pass {upstream};
    }}
}}
"""

_HTTP_REDIRECT_TEMPLATE = """# generated by WAF backend - do not edit manually
server {{
{listen_lines}    server_name {domain};
""" + _ACME_CHALLENGE_LOCATION + """    location / {{
        return 301 {redirect_url};
    }}
}}
"""


def _resolve_ssl_paths(site: Site) -> tuple[str | None, str | None]:
    if site.certificate_id and site.certificate:
        return site.certificate.cert_path, site.certificate.key_path
    return None, None


def _format_listen_lines(ports: list[int], *, ssl: bool = False) -> str:
    suffix = " ssl" if ssl else ""
    return "".join(f"    listen {port}{suffix};\n" for port in ports)


def _http_listen_line(site: Site, http_ports: list[int]) -> str:
    force_https = bool(getattr(site, "force_https", False))
    if site.listen_http and not force_https and http_ports:
        return _format_listen_lines(http_ports)
    return ""


def _https_listen_line(site: Site, https_ports: list[int], has_ssl: bool) -> str:
    if site.listen_https and has_ssl and https_ports:
        return _format_listen_lines(https_ports, ssl=True)
    if site.listen_https:
        log.warning(
            "site %s (id=%s): listen_https=true but ssl cert/key missing, skip HTTPS listen",
            site.domain,
            site.id,
        )
    return ""


def _render_proxy_server(
    site: Site,
    *,
    server_names: str,
    listen_lines: str,
    ssl_block: str,
    real_ip_block: str,
    proxy_buffering_line: str,
    upstream: str,
) -> str:
    """One server block with a static proxy_pass (http:// or https://)."""
    return _FIXED_TEMPLATE.format(
        site_id=site.id,
        domain=server_names,
        listen_lines=listen_lines,
        ssl_block=ssl_block,
        real_ip_block=real_ip_block,
        proxy_buffering_line=proxy_buffering_line,
        upstream=upstream,
    )


def _real_ip_block(site: Site) -> str:
    source = getattr(site, "client_ip_source", None) or "remote_addr"
    header = REAL_IP_HEADER_BY_SOURCE.get(source)
    if not header:
        return ""
    return (
        f"    # client IP source: {source} ({header})\n"
        "    set_real_ip_from 0.0.0.0/0;\n"
        "    set_real_ip_from ::/0;\n"
        f"    real_ip_header {header};\n"
        "    real_ip_recursive on;\n"
    )


def _http_redirect_block(
    site: Site,
    server_names: str,
    has_ssl: bool,
    http_ports: list[int],
    https_ports: list[int],
) -> str:
    force_https = bool(getattr(site, "force_https", False))
    if not force_https or not site.listen_https or not has_ssl or not http_ports:
        return ""
    return _HTTP_REDIRECT_TEMPLATE.format(
        listen_lines=_format_listen_lines(http_ports),
        domain=server_names,
        redirect_url=https_redirect_url(https_ports),
    )


def _proxy_buffering_line(site: Site) -> str:
    """Emit proxy_buffering off when the site opts out of response buffering."""
    if bool(getattr(site, "disable_content_buffering", False)):
        return "        proxy_buffering off;\n"
    return ""


def render_site(site: Site) -> str:
    cert_path, key_path = _resolve_ssl_paths(site)
    has_ssl = bool(cert_path and key_path)
    http_ports = resolve_http_listen_ports(site)
    https_ports = resolve_https_listen_ports(site)
    http_listen = _http_listen_line(site, http_ports)
    https_listen = _https_listen_line(site, https_ports, has_ssl)
    listen_lines = http_listen + https_listen
    server_names = " ".join(site_domain_list(site))
    redirect_block = _http_redirect_block(
        site, server_names, has_ssl, http_ports, https_ports
    )

    if not listen_lines.strip() and not redirect_block:
        log.warning(
            "site %s (id=%s): no listen ports configured, skip conf generation",
            site.domain,
            site.id,
        )
        return ""

    if not listen_lines.strip():
        return redirect_block

    ssl_block = ""
    if site.listen_https and has_ssl:
        ssl_block = (
            f"    ssl_certificate {cert_path};\n"
            f"    ssl_certificate_key {key_path};\n"
        )

    upstream_http = build_upstream_url(
        site.origin_host, "http", site.origin_http_port
    )
    upstream_https = build_upstream_url(
        site.origin_host, "https", site.origin_https_port
    )
    real_ip_block = _real_ip_block(site)
    proxy_buffering_line = _proxy_buffering_line(site)

    if site.origin_protocol == "follow":
        # Split listeners: variable proxy_pass (map $scheme) cannot reliably
        # switch http:// vs https:// at runtime. Static proxy_pass per scheme
        # matches the already-working fixed-protocol path.
        parts: list[str] = []
        if http_listen:
            parts.append(
                _render_proxy_server(
                    site,
                    server_names=server_names,
                    listen_lines=http_listen,
                    ssl_block="",
                    real_ip_block=real_ip_block,
                    proxy_buffering_line=proxy_buffering_line,
                    upstream=upstream_http,
                )
            )
        if https_listen:
            parts.append(
                _render_proxy_server(
                    site,
                    server_names=server_names,
                    listen_lines=https_listen,
                    ssl_block=ssl_block,
                    real_ip_block=real_ip_block,
                    proxy_buffering_line=proxy_buffering_line,
                    upstream=upstream_https,
                )
            )
        main_block = "\n".join(parts)
    else:
        if site.origin_protocol == "http":
            upstream = upstream_http
        else:
            upstream = upstream_https
        main_block = _render_proxy_server(
            site,
            server_names=server_names,
            listen_lines=listen_lines,
            ssl_block=ssl_block,
            real_ip_block=real_ip_block,
            proxy_buffering_line=proxy_buffering_line,
            upstream=upstream,
        )

    if redirect_block:
        return f"{redirect_block}\n{main_block}"
    return main_block


def _engine_is_running() -> bool:
    """Return True if nginx.pid exists and the OpenResty master is alive."""
    try:
        with open(ENGINE_PID_PATH, encoding="utf-8") as f:
            pid = int(f.read().strip())
    except (OSError, ValueError):
        return False
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


async def regenerate(
    db: AsyncSession,
    *,
    skip_reload_if_engine_down: bool = False,
) -> EngineReloadResult:
    """Rewrite conf.d for all enabled sites, drop stale files, trigger reload.

    Returns an EngineReloadResult. Conf files are always written first;
    callers that already committed DB state should treat failure as soft.

    Args:
        db: Session used to load sites and engine settings.
        skip_reload_if_engine_down: When True, write conf.d but skip
            ``openresty -s reload`` if the engine is not running yet
            (cold start). Default False keeps existing caller behavior.

    Returns:
        Reload result. ``ok`` is True when reload succeeded, or when reload
        was skipped because the engine had not started.
    """
    conf_dir = settings.engine_conf_dir
    os.makedirs(conf_dir, exist_ok=True)

    from app.services import waf_settings as waf_settings_svc

    row = await waf_settings_svc.get_or_create(db)
    snippet_error: str | None = None
    try:
        apply_client_max_body_size(
            int(getattr(row, "max_upload_size_mb", None) or DEFAULT_MAX_UPLOAD_SIZE_MB)
        )
        apply_origin_read_timeout(
            int(
                getattr(row, "origin_read_timeout_sec", None)
                or DEFAULT_ORIGIN_READ_TIMEOUT_SEC
            )
        )
    except OSError as exc:
        snippet_error = str(exc).strip() or exc.__class__.__name__
        log.error("failed to write engine http snippets: %s", exc)

    sites = (
        await db.execute(
            select(Site).options(selectinload(Site.certificate))
        )
    ).scalars().all()
    wanted = {}
    for s in sites:
        if s.enabled:
            content = render_site(s)
            if content:
                wanted[f"site_{s.id}.conf"] = content

    # write wanted files
    for fname, content in wanted.items():
        path = os.path.join(conf_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    # remove stale generated files
    for fname in os.listdir(conf_dir):
        if fname.startswith("site_") and fname.endswith(".conf") and fname not in wanted:
            try:
                os.remove(os.path.join(conf_dir, fname))
            except OSError:
                pass

    if snippet_error:
        result = EngineReloadResult(ok=False, reason="engine", detail=snippet_error)
        log.info(
            "regenerated %d site confs (reload_ok=%s reason=%s detail=%s)",
            len(wanted),
            result.ok,
            result.reason,
            (result.detail or "")[:200],
        )
        return result

    # Cold start: engine waits for /health, so pid is not there yet. Conf is
    # already on disk; OpenResty will load it on first start. Do not call
    # ``openresty -s reload`` (that would log nginx.pid ENOENT).
    if skip_reload_if_engine_down and not _engine_is_running():
        log.info(
            "regenerated %d site confs (reload skipped: engine not running yet)",
            len(wanted),
        )
        return EngineReloadResult(ok=True)

    result = await trigger_reload()
    log.info(
        "regenerated %d site confs (reload_ok=%s reason=%s detail=%s)",
        len(wanted),
        result.ok,
        result.reason,
        (result.detail or "")[:200],
    )
    return result


def _reload_engine_sync() -> EngineReloadResult:
    """Reload OpenResty as the backend process (root); Lua workers cannot.

    Returns a soft-failure result when the engine is down or reload fails —
    site rows may already be committed and must not be rolled back by this step.
    """
    try:
        subprocess.run(
            ENGINE_RELOAD_CMD,
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
        log.info("engine nginx reload OK")
        return EngineReloadResult(ok=True)
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or "").strip() or f"openresty reload exit {exc.returncode}"
        reason = classify_reload_error(detail)
        log.error(
            "engine nginx reload failed (exit %s reason=%s): %s",
            exc.returncode,
            reason,
            detail,
        )
        return EngineReloadResult(ok=False, reason=reason, detail=detail)
    except subprocess.TimeoutExpired as exc:
        detail = f"openresty reload timed out after {exc.timeout}s"
        log.error("engine nginx reload failed: %s", detail)
        return EngineReloadResult(ok=False, reason="engine", detail=detail)
    except OSError as exc:
        detail = str(exc).strip() or exc.__class__.__name__
        log.error("engine nginx reload failed: %s", detail)
        return EngineReloadResult(ok=False, reason="engine", detail=detail)


async def trigger_reload() -> EngineReloadResult:
    """Bump reload version and reload OpenResty so conf.d changes take effect."""
    await get_redis().incr(RELOAD_KEY)
    return await asyncio.to_thread(_reload_engine_sync)